#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
